---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: latest
    pkg:
      - mysql-server-8.0
      - python3-pymysql
- name: Create a new database with name 'wordpress_db'
  become: true
  community.mysql.mysql_db:
    name: '{{ wordpress_db_name }}'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
- name: Create database user with name 'wordpress_user' and password '12345' with all database privileges
  become: true
  community.mysql.mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_user_password }}"
    priv: '{{ wordpress_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
    column_case_sensitive: false
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
    host: '{{ item }}'
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - '{{ wordpress_server_url }}'
    - '{{ wordpress_server_url }}.lxd'
- name: Replace bind address to allow access from network (requires Ansible >= 2.4)
  become: true
  notify:
    - restart mysql
  ansible.builtin.replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

