---
- hosts: wordpress
  handlers:
    - name: restart apache
      become: yes
      ansible.builtin.service:
        name: apache2
        state: restarted
      
  tasks:
    - name: Install dependencies
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        state: latest
        pkg:
          - apache2
          - ghostscript
          - libapache2-mod-php
          - mysql-server-8.0
          - php
          - php-bcmath
          - php-curl
          - php-imagick
          - php-intl
          - php-json
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip
          - python3-pymysql
    - name: Create a new database with name 'wordpress_db'
      become: yes
      community.mysql.mysql_db:
        name: wordpress_db
        stage: present
        login_unix_socket: /run/mysqld/mysqld.sock

