---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: latest
    pkg:
      - apache2
      - ghostscript
      - libapache2-mod-php
      - php
      - php-bcmath
      - php-curl
      - php-imagick
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip

